# Generated by Django 3.2.16 on 2023-11-15 23:37

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Введите номер в формате: '79XXXXXXXXX'", regex='^79[0-9]{9}$')], verbose_name='Номер телефона')),
                ('operator_code', models.CharField(max_length=3, verbose_name='Код оператора')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='Тег')),
                ('time_zone', models.IntegerField(choices=[(0, '(UTC)'), (1, '(UTC+1)'), (2, 'Калининградское (UTC+2)'), (3, 'Московское (UTC+3)'), (4, 'Самарское (UTC+4)'), (5, 'Екатеринбургское (UTC+5)'), (6, 'Омское (UTC+6)'), (7, 'Красноярское (UTC+7)'), (8, 'Иркутское (UTC+8)'), (9, 'Якутское (UTC+9)'), (10, 'Владивостокское (UTC+10)'), (11, 'Магаданское (UTC+11)'), (12, 'Камчатское (UTC+12)'), (13, '(UTC+13)'), (14, '(UTC+14)'), (15, '(UTC+15)'), (16, '(UTC+16)'), (17, '(UTC+17)'), (18, '(UTC+18)'), (19, '(UTC+19)'), (20, '(UTC+20)'), (21, '(UTC+21)'), (22, '(UTC+22)'), (23, '(UTC+23)')], default=0, verbose_name='Время (Часовой пояс)')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавивший аккаунт')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start_sending', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало рассылки')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('filter_operator_code', models.CharField(blank=True, max_length=100, verbose_name='Фильтр мобильных операторов')),
                ('filter_tag', models.CharField(blank=True, max_length=100, verbose_name='Фильтр тегов')),
                ('date_time_end_sending', models.DateTimeField(default=datetime.datetime(2023, 11, 16, 23, 37, 11, 109217, tzinfo=utc), verbose_name='Конец рассылки')),
                ('active', models.BooleanField(default=True, verbose_name='Рассылать сообщения')),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('stopped', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавивший аккаунт')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_of_dispatch', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время отправки')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Ожидает отправки'), (1, 'Отправлено'), (2, 'Не отправлено. Дата и время клиента больше выбранного в рассылке'), (3, 'Не отправлено. Ошибка внешнего API')], verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.client', verbose_name='Клиент')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
